### ISSUE TITLE
Set padding on multiple layers within a symbol

### ISSUE THREAD

**Issue by stevemdixon** [DWilliames/paddy-sketch-plugin#70]
### Feature request / enhancement

I tend to construct button components like this:

- A text layer
- A symbol (this symbol contains a single rectangle with a solid color)
- A mask (this helps me get border radii on my buttons)

When I use this plugin, the padding is applied to the "mask" layer—as expected given it is the layer furthest to the back—except I'd like it to be applied to both the symbol and the mask. I feel this might be a huge ask. I'd be happy to help develop this feature out, too, if that's an option!

**Comment by mikeozornin** [comment]
You can do it with Paddy now.

Here is how:
1. Create BG for buttons as a symbol. If you want to override border radius too, than create two symbols: BG only and masked BG.
2. Create symbol of button from: button BG symbol, text and icon symbol. Mark text with paddings and set correct symbol resize options for other elements.
3. Profit! Paddy autoresize will work fine.

I attached example file. All buttons on Page 1 are instances of the same symbol. Try to change text and look at resize. Preview: <img width="282" alt="screen shot 2018-03-08 at 17 35 11" src="https://user-images.githubusercontent.com/1744928/37156405-13a5701e-22f7-11e8-8c59-7bb290365dc9.png">

Sketch-file: [paddy-example.sketch.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/1793516/paddy-example.sketch.zip)

Feel free to ask for help, if you need.

**Comment by fancymans** [comment]
Padding-right breaks when wrapping the Paddy elements with another set of padding.

![screen shot 2018-03-09 at 6 21 51 pm](https://user-images.githubusercontent.com/7216440/37237378-3c9d16a4-23c7-11e8-979a-3b2d919130d6.png)
![screen shot 2018-03-09 at 6 23 13 pm](https://user-images.githubusercontent.com/7216440/37237382-3fd95d5a-23c7-11e8-9ed0-b1a7866a3a4f.png)

**Comment by mikeozornin** [comment]
I fixed you solution: I moved padding settings to mask and add - to BG symbol.
You symbols must calculate padding only from the text layer (set - to other layers). Paddy will resize whole symbol to a new size. If you set sketch resize properly you will get what you need:
<img width="434" alt="screen shot 2018-03-10 at 12 20 37" src="https://user-images.githubusercontent.com/1744928/37240516-77cfb6dc-245d-11e8-8484-2595ef746f0e.png">

If you what to have several buttons with different border radius you can try to use nested symbols:
<img width="499" alt="screen shot 2018-03-10 at 12 21 43" src="https://user-images.githubusercontent.com/1744928/37240526-b4ec3432-245d-11e8-8073-ad2bc175e6fa.png">

[paddy-examples.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/1799225/paddy-examples.zip)

**Comment by mikeozornin** [comment]
Maybe having multiple paddings will be good, but you don't need it in simple cases.

**Comment by DWilliames** [comment]
Thanks heaps @mikeozornin for helping out responding to this!! :) 

Yeah; right now Paddy doesn't support 'multiple' layers being the 'Padding' layer within the same group. It could cause some conflicts with how it is currently set up.

I think @mikeozornin has proceeded a great example of how you can do it currently. So for now I will close this feature request; as I'm not sure if it is actually necessary. 👍

**Comment by fancymans** [comment]
Was able to test and it works like a charm. Thanks for the help @mikeozornin! ;)

**Comment by stevemdixon** [comment]
Unfortunately, I'm still unable to get the desired effect. My symbol contains the following layers:

```
Text layer 1
Text layer 2
Text layer 3
Background Color (Symbol)
Mask
```

To give more context, this button component setup allows me to create multiple styles of button from a single component. For example, I can use Text layer 2, switch up the background color with another color (all my colors are symbols, to allow switching like this). The reason for the mask is so that I can ensure each button have corner radii.

**Comment by mikeozornin** [comment]
As for me, you have a very strange symbol organization ;–)

I tried to create your button in Sketch:
<img width="248" alt="screen shot 2018-03-13 at 23 45 04" src="https://user-images.githubusercontent.com/1744928/37368948-c3864bf0-2718-11e8-9429-281b24dc9450.png">

And source file: [paddy-6-text-styles-example.sketch.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/1808605/paddy-6-text-styles-example.sketch.zip)

If I'm wrong, please attach sketch source file, I'll try to help you.

**Comment by stevemdixon** [comment]
Hey, @mikeozornin! Nope, you've got it spot on there! Even then, downloading your Sketch file, the resizing doesn't work for me. 🤔

**Comment by mikeozornin** [comment]
🤔 I just had the same on my work desktop. The same plugin, same sketch version, same file and resize didn't work.

I enter button symbol editing, select any layer (e.g. mask) and deselect it. Paddy showed symbol instances update.
![screen shot 2018-03-14 at 13 11 56](https://user-images.githubusercontent.com/1744928/37396254-6e98757a-2789-11e8-80a7-59c27a1114ba.png)

After that resizing started again. Maybe the same magic trick will help to you too.
